name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - warnings
  - xarray
  - os
  - urllib.request
  - tqdm
  - matplotlib
  - cartopy
  - numpy
  - ipython
  - plotly
  - io
  - pybase64
  - pillow
  - ipyleaflet
  - ipywidgets
  
  
